#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

/* ===================================================================
 * DEFINES DE PREPROCESADOR
 * ===================================================================*/

// ARCHIVOS
#define ARCHIVO_VENDEDORES "vendedores.dat"
#define ARCHIVO_CLIENTES "clientes.dat"
#define ARCHIVO_PRODUCTOS "productos.dat"
#define ARCHIVO_VENTAS "ventas.dat"
#define ARCHIVO_DETALLE_VENTAS "detalles_ventas.dat"
// TECLAS
#define TECLA_ARRIBA 14
#define TECLA_ABAJO 15
#define TECLA_ENTER 1
#define TECLA_F3 20
#define TECLA_ESC 27
#define TECLA_BACKSPACE 8
#define TECLA_ESPACIO 32

#define ASCII_IMPRIMIBLE_MAX 126
#ifdef _WIN32
    #define ASCII_ESQUINA_IZQUIERDA 201
    #define ASCII_ESQUINA_DERECHA 187
    #define ASCII_BARRA_VERTICAL 186
    #define ASCII_BARRA_HORIZONTAL 205
    #define ASCII_BARRA_EMPALME_DERECHA 204
    #define ASCII_BARRA_EMPALME_IZQUIERDA 185
    #define ASCII_BARRA_EMPALME_IZQUIERDA_INFERIOR 200
    #define ASCII_BARRA_EMPALME_HORIZONTAL_ARRIBA 202
    #define ASCII_BARRA_ESQUINA_DERECHA_INFERIOR 188
    #define ASCII_BARRA_DOBLE_CRUCE 206
    #define ASCII_BARRA_EMPALME_ABAJO 203
#else
    // Valores para mi linu
    #define ASCII_ESQUINA_IZQUIERDA "╔"
    #define ASCII_ESQUINA_DERECHA "╗"
    #define ASCII_BARRA_VERTICAL "║"
    #define ASCII_BARRA_HORIZONTAL "═"
    #define ASCII_BARRA_EMPALME_DERECHA "╠"
    #define ASCII_BARRA_EMPALME_IZQUIERDA "╣"
    #define ASCII_BARRA_EMPALME_IZQUIERDA_INFERIOR "╚"
    #define ASCII_BARRA_EMPALME_HORIZONTAL_ARRIBA "╩"
    #define ASCII_BARRA_ESQUINA_DERECHA_INFERIOR "╝"
    #define ASCII_BARRA_DOBLE_CRUCE "╬"
    #define ASCII_BARRA_EMPALME_ABAJO "╦"
#endif

// MODELOS
#define MAX_NOMBRE 31
#define MAX_TELEFONO 16
#define MAX_DNI 9
#define TELEFONO_MIN_DIGITOS 10

// CONSTANTES DE UI PARA PRODUCTO
#define PRODUCTO_OPCIONES_MENU 5
#define PRODUCTO_OPCIONES_CARGA 7
#define PRODUCTO_INICIO_TITULO 3
#define PRODUCTO_INICIO_TABLA (PRODUCTO_INICIO_TITULO + 5)
#define PRODUCTO_CURSOR_START_X 3
#define PRODUCTO_CURSOR_START_Y 4
#define PRODUCTO_PAGINADO 15

// CONSTANTES DE UI PARA CLIENTE
#define CLIENTE_OPCIONES_MENU 4
#define CLIENTE_OPCIONES_CARGA 3
#define CLIENTE_INICIO_TITULO 3
#define CLIENTE_INICIO_TABLA (CLIENTE_INICIO_TITULO + 5)
#define CLIENTE_CURSOR_START_X 30
#define CLIENTE_CURSOR_START_Y 4
#define CLIENTE_PAGINADO 15

// CONSTANTES DE UI PARA VENDEDOR
#define VENDEDOR_OPCIONES_MENU 5
#define VENDEDOR_OPCIONES_CARGA 6
#define VENDEDOR_INICIO_TITULO 3
#define VENDEDOR_INICIO_TABLA (VENDEDOR_INICIO_TITULO + 5)
#define VENDEDOR_CURSOR_START_X 12
#define VENDEDOR_CURSOR_START_Y 4
#define VENDEDOR_PAGINADO 15

// CONSTANTES DE UI PARA VENTA
#define VENTA_OPCIONES 6 // Usado en cargar() y mostrar()
#define VENTA_INICIO_TITULO 3
#define VENTA_INICIO_TABLA (VENTA_INICIO_TITULO + 5)
#define VENTA_CURSOR_START_X 9
#define VENTA_CURSOR_START_Y 4
#define VENTA_PAGINADO 15

// CONSTANTES DE UI PARA menuVenta
#define MENU_VENTA_OPCIONES 4 // (Agregar, Mostrar, Info, Salir)



#endif // CONSTANTES_H_INCLUDED
